### ISSUE TITLE
Support initialization of database

### ISSUE THREAD

**Issue by TamalSaha** [k8sdb/postgres#3]
https://kubernetes.io/docs/concepts/abstractions/init-containers/

**Comment by aerokite** [comment]
Init containers run before app Containers. So before running postgres container, no way to run any script that needs access to postgres database. 

What are you actually proposing here?

**Comment by TamalSaha** [comment]
Yes. we can't just init containers. I stand corrected,

But my general point is that:
- User should be able to run a command to init DB. This can be a sql script or this can be any command they so choose. We should enable this. For example, in AppsCode, we need to run migrator. QI had similar requirements.

So, we should make it generic. We can talk offline.

**Comment by aerokite** [comment]
We need to support this in other ways. 
Closing this issue.

**Comment by TamalSaha** [comment]
Let's leave this open, as a tracking issue.
